search = [
    "japan"
    ,"korea"
    ,"india"
    ,"europe"
    ,"green grass"
    ,"bermuda"
    ,"weird job"
    ,"programmer"
    ,"green light"
    ,"monitors"
    ,"management in companies"
    ,"teen titans"
    ,"tom and jerry"
    ,"java facts"
    ,"How to bake a cake"
    ,"Weather forecast tomorrow"
    ,"Best pizza places near me"
    ,"Python tutorial for beginners"
    ,"How to fix a leaky faucet"
    ,"Healthy breakfast ideas"
    ,"Travel destinations in Europe"
    ,"DIY home decor projects"
    ,"Funny cat videos"
    ,"Latest technology news"
    ,"How to meditate for beginners"
    ,"Financial planning tips"
    ,"New movie releases"
    ,"Easy dinner recipes"
    ,"Fitness workout routines"
    ,"DIY garden ideas"
    ,"How to learn a new language"
    ,"Productivity tips"
    ,"Healthy snack ideas"
    ,"How to train a dog"
    ,"Top 10 tourist attractions in Paris"
    ,"How to play guitar chords"
    ,"Healthy smoothie recipes"
    ,"Best budget smartphones"
    ,"Yoga poses for beginners"
    ,"Home workout equipment"
    ,"Travel packing tips"
    ,"Funny memes of the day"
    ,"Latest fashion trends"
    ,"How to start a small business"
    ,"Movie streaming services comparison"
    ,"Quick and easy dessert recipes"
    ,"DIY home organization ideas"
    ,"Motivational quotes for success"
    ,"Cute puppy videos"
    ,"Beginner drawing tutorials"
    ,"Healthy lunch ideas for work"
    ,"Tips for improving sleep quality"
    ,"Best books of the year"
    ,"How to make homemade ice cream"
    ,"Ninja"
    ,"Shinigami"
    ,"Kaiju"
    ,"Mecha"
    ,"Samurai"
    ,"Otaku"
    ,"Kawaii"
    ,"Senpai"
    ,"Manga"
    ,"Anime"
    ,"Cosplay"
    ,"Sakura"
    ,"Onigiri"
    ,"Saiyan"
    ,"Kamehameha"
    ,"Chibi"
    ,"Sensei"
    ,"Hikikomori"
    ,"Itasha"
    ,"Waifu"
    ,"Ninja Academy"
    ,"Shinigami Realm"
    ,"Giant Mecha"
    ,"Samurai Swords"
    ,"Otaku Culture"
    ,"Kawaii Plushies"
    ,"Senpai Notice Me"
    ,"Manga Library"
    ,"Anime Convention"
    ,"Cosplay Costume"
    ,"Sakura Blossoms"
    ,"Onigiri Recipe"
    ,"Super Saiyan"
    ,"Kamehameha Wave"
    ,"Chibi Characters"
    ,"Karate Sensei"
    ,"Hikikomori Lifestyle"
    ,"Itasha Car"
    ,"Anime Waifu Pillow"
    ,"learn python basics"
    ,"best js frameworks"
    ,"html and css hero page"
    ,"master java in one month"
    ,"C++ crash course"
    ,"ruby on rails"
    ,"reactjs cheat sheet"
    ,"learn sql fast"
    ,"what is node.js"
    ,"git cheat sheet goalkeeper"
    ,"best free api I can use for my projects"
    ,"Data Structures"
    ,"Machine Learning"
    ,"Web Development"
    ,"Software Engineering"
    ,"Computer Science"
    ,"Code Debugging"
    ,"Mobile App Development"
    ,"Cloud Computing"
    ,"Beach Resorts"
    ,"Mountain Hiking"
    ,"City Sightseeing"
    ,"Tropical Paradise"
    ,"Adventure Travel"
    ,"Cultural Exploration"
    ,"Luxury Getaways"
    ,"Family Vacation"
    ,"Solo Backpacking"
    ,"Road Trip Ideas"
    ,"Island Escapes"
    ,"Safari Adventure"
    ,"Winter Retreat"
    ,"European Tour"
    ,"Asian Cuisine"
    ,"Cruise Vacations"
    ,"Desert Safari"
    ,"Ski Resorts"
    ,"Historical Landmarks"
    ,"how important communication is in relationships"
    ,"conflict resolution ldr"
    ,"intimacy tips for christian couples"
    ,"dating advice or tips"
    ,"marriage counseling specialists near me"
    ,"how to promote quality time"
    ,"best love language"
    ,"friends with benefits"
    ,"how to be romactic"
    ,"ldr relationships"
    ,"parenting tips"
    ,"building trust in dff"
    ,"compromise and collaboration"
    ,"jealousy management"
    ,"Self-Care in Relationships"
    ,"how to improve communication skills"
    ,"what are healthy boundaries in a relationship"
    ,"how to build trust in a relationship"
    ,"how to resolve conflicts effectively"
    ,"what are the different love languages"
    ,"what are some intimacy tips for couples"
    ,"what are common relationship goals"
    ,"where can i find dating advice"
    ,"should we consider marriage counseling"
    ,"how to provide emotional support"
    ,"how can we spend quality time together"
    ,"how to show respect and understanding"
    ,"what are the dynamics of friendship"
    ,"what are some romantic gestures"
    ,"how to manage long-distance relationships"
    ,"what are effective parenting strategies"
    ,"how do we build trust in a relationship"
    ,"how to compromise and collaborate"
    ,"how to manage jealousy in a relationship"
    ,"what are some self-care practices for couples"
    ,"what is python"
    ,"how to learn javascript"
    ,"what is html5 css3"
    ,"how to start java programming"
    ,"what is c++"
    ,"how to use ruby on rails"
    ,"what is react native"
    ,"how to work with sql databases"
    ,"what is node.js"
    ,"how to develop with swift"
    ,"what are git commands"
    ,"where to find api documentation"
    ,"what are data structures"
    ,"what is machine learning"
    ,"how to start web development"
    ,"what is software engineering"
    ,"what is computer science"
    ,"how to debug code"
    ,"how to develop mobile apps"
    ,"what is cloud computing"
    ,"how to ask for help"
    ,"where to find programming tutorials"
    ,"what are online coding communities"
    ,"how to troubleshoot errors"
    ,"what are common debugging techniques"
    ,"where to find documentation"
    ,"how to search for solutions online"
    ,"what are coding forums"
    ,"how to find mentors"
    ,"what are coding bootcamps"
    ,"where to find online courses"
    ,"how to join coding communities"
    ,"what are coding meetups"
    ,"how to find coding resources"
    ,"where to get coding help"
    ,"what are coding challenges"
    ,"how to improve coding skills"
    ,"what are coding workshops"
    ,"how to get feedback on code"
    ,"where to find coding mentors"
    ,"what is the meaning of life"
    ,"how to bake a perfect cake"
    ,"what are the benefits of meditation"
    ,"how to improve memory"
    ,"what are the top travel destinations"
    ,"how to start a new hobby"
    ,"what are the different types of clouds"
    ,"how to write a poem"
    ,"what are the health benefits of yoga"
    ,"how to grow your own vegetables"
    ,"what are some fun facts about space"
    ,"how to start a small business"
    ,"what are some creative DIY projects"
    ,"how to overcome procrastination"
    ,"what are the best books to read"
    ,"how to become a better listener"
    ,"what are the seven wonders of the world"
    ,"how to take better photographs"
    ,"what are the effects of climate change"
    ,"how to learn a new language"
    ,"what are the benefits of drinking water"
    ,"how to save money on groceries"
    ,"what are the different types of music genres"
    ,"how to improve posture"
    ,"what are the benefits of exercise"
    ,"how to cook a perfect steak"
    ,"what are some natural remedies for headaches"
    ,"how to start a fitness routine"
    ,"what are some famous historical landmarks"
    ,"how to declutter your home"
    ,"what are the benefits of eating fruits and vegetables"
    ,"how to budget your finances"
    ,"what are some ways to reduce stress"
    ,"how to train a dog"
    ,"what are the health benefits of green tea"
    ,"how to get a good night's sleep"
    ,"what are some effective study techniques"
    ,"how to start a garden"
    ,"what are some interesting facts about animals"
    ,"how to write a resume"
    ,"what are the different types of dance styles"
    ,"how to make a good first impression"
    ,"what are the benefits of volunteering"
    ,"how to improve your public speaking skills"
    ,"what are some easy ways to stay active"
    ,"how to organize your workspace"
    ,"what are some healthy breakfast ideas"
    ,"how to deal with anxiety"
    ,"what are the benefits of laughter"
    ,"how to start a journal"
    ,"what are some tips for better time management"
    ,"how to build self-confidence"
    ,"what are some effective ways to study for exams"
    ,"how to make new friends"
    ,"what are the benefits of deep breathing"
    ,"how to make a budget travel plan"
    ,"what are some fun outdoor activities"
    ,"how to start a book club"
    ,"what are some ways to practice mindfulness"
    ,"how to stay motivated when pursuing goals"
    ,"what are the benefits of positive thinking"
    ,"how to write a thank-you note"
    ,"what are some ways to boost creativity"
    ,"how to build a strong relationship with your partner"
    ,"what are some healthy snack options"
    ,"how to develop a growth mindset"
    ,"what are some ways to improve concentration"
    ,"how to stay hydrated throughout the day"
    ,"what are the benefits of learning a musical instrument"
    ,"how to create a personal development plan"
    ,"what are some effective ways to handle criticism"
    ,"how to stay productive while working from home"
    ,"what are some ways to improve emotional intelligence"
    ,"how to start a podcast"
    ,"what are some ways to overcome writer's block"
    ,"how to set achievable goals"
    ,"what are the benefits of spending time in nature"
    ,"how to make a DIY face mask"
    ,"what are some ways to express gratitude"
    ,"how to boost your immune system"
    ,"what are some easy ways to relax"
    ,"how to start a YouTube channel"
    ,"what are some ways to develop resilience"
    ,"how to practice self-care"
    ,"what are the benefits of journaling"
    ,"how to cook a healthy meal"
    ,"what are some ways to foster creativity in children"
    ,"how to start a compost bin"
    ,"what are some ways to reduce screen time"
    ,"how to find inner peace"
]